[2024-02-26T07:07:44.641-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline.saving_to_csv manual__2024-02-26T12:07:35.313328+00:00 [queued]>
[2024-02-26T07:07:44.644-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline.saving_to_csv manual__2024-02-26T12:07:35.313328+00:00 [queued]>
[2024-02-26T07:07:44.644-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-02-26T07:07:44.650-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): saving_to_csv> on 2024-02-26 12:07:35.313328+00:00
[2024-02-26T07:07:44.652-0500] {standard_task_runner.py:57} INFO - Started process 87047 to run task
[2024-02-26T07:07:44.656-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_pipeline', 'saving_to_csv', 'manual__2024-02-26T12:07:35.313328+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/postgres_pipeline.py', '--cfg-path', '/var/folders/0j/ct19m_4d33qfzqs3tkf7s7rm0000gq/T/tmp8b5y9ut5']
[2024-02-26T07:07:44.657-0500] {standard_task_runner.py:85} INFO - Job 44: Subtask saving_to_csv
[2024-02-26T07:07:44.674-0500] {task_command.py:416} INFO - Running <TaskInstance: postgres_pipeline.saving_to_csv manual__2024-02-26T12:07:35.313328+00:00 [running]> on host venkatasaismbp.mynetworksettings.com
[2024-02-26T07:07:44.701-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Venkata' AIRFLOW_CTX_DAG_ID='postgres_pipeline' AIRFLOW_CTX_TASK_ID='saving_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T12:07:35.313328+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T12:07:35.313328+00:00'
[2024-02-26T07:07:44.705-0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/dags/postgres_pipeline.py", line 17, in saving_to_csv
    writer = csv.writer(file)
             ^^^
NameError: name 'csv' is not defined
[2024-02-26T07:07:44.708-0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=postgres_pipeline, task_id=saving_to_csv, execution_date=20240226T120735, start_date=20240226T120744, end_date=20240226T120744
[2024-02-26T07:07:44.712-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 44 for task saving_to_csv (name 'csv' is not defined; 87047)
[2024-02-26T07:07:44.717-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-02-26T07:07:44.723-0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
