[2024-02-27T23:12:25.259-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_customer_dag.upload_to_s3 manual__2024-02-28T04:09:53.320788+00:00 [queued]>
[2024-02-27T23:12:25.281-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_customer_dag.upload_to_s3 manual__2024-02-28T04:09:53.320788+00:00 [queued]>
[2024-02-27T23:12:25.287-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-02-27T23:12:25.314-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-02-28 04:09:53.320788+00:00
[2024-02-27T23:12:25.323-0500] {standard_task_runner.py:57} INFO - Started process 49129 to run task
[2024-02-27T23:12:25.340-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_customer_dag', 'upload_to_s3', 'manual__2024-02-28T04:09:53.320788+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/etl_customer_dag.py', '--cfg-path', '/var/folders/0j/ct19m_4d33qfzqs3tkf7s7rm0000gq/T/tmpucxa57v8']
[2024-02-27T23:12:25.353-0500] {standard_task_runner.py:85} INFO - Job 86: Subtask upload_to_s3
[2024-02-27T23:12:25.488-0500] {task_command.py:416} INFO - Running <TaskInstance: etl_customer_dag.upload_to_s3 manual__2024-02-28T04:09:53.320788+00:00 [running]> on host venkatasaismbp.mynetworksettings.com
[2024-02-27T23:12:25.605-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Venkata' AIRFLOW_CTX_DAG_ID='etl_customer_dag' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-28T04:09:53.320788+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-28T04:09:53.320788+00:00'
[2024-02-27T23:12:25.624-0500] {base.py:73} INFO - Using connection ID 'aws_conn_s3' for task execution.
[2024-02-27T23:12:25.624-0500] {connection_wrapper.py:382} INFO - AWS Connection (conn_id='aws_conn_s3', conn_type='aws') credentials retrieved from login and ***.
[2024-02-27T23:13:16.091-0500] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-02-27T23:13:16.105-0500] {process_utils.py:131} INFO - Sending 15 to group 49129. PIDs of all processes in the group: [49129]
[2024-02-27T23:13:16.106-0500] {process_utils.py:86} INFO - Sending the signal 15 to group 49129
[2024-02-27T23:14:16.130-0500] {process_utils.py:149} WARNING - process psutil.Process(pid=49129, name='Python', status='running', started='23:12:25') did not respond to SIGTERM. Trying SIGKILL
[2024-02-27T23:14:16.138-0500] {process_utils.py:86} INFO - Sending the signal 9 to group 49129
[2024-02-27T23:14:16.156-0500] {process_utils.py:79} INFO - Process psutil.Process(pid=49129, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='23:12:25') (49129) terminated with exit code -9
[2024-02-27T23:14:16.159-0500] {standard_task_runner.py:172} ERROR - Job 86 was killed before it finished (likely due to running out of memory)
