[2024-02-27T23:13:08.931-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_customer_dag.read_s3_file_task manual__2024-02-28T04:09:53.320788+00:00 [queued]>
[2024-02-27T23:13:08.946-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_customer_dag.read_s3_file_task manual__2024-02-28T04:09:53.320788+00:00 [queued]>
[2024-02-27T23:13:08.947-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-02-27T23:13:08.974-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): read_s3_file_task> on 2024-02-28 04:09:53.320788+00:00
[2024-02-27T23:13:08.981-0500] {standard_task_runner.py:57} INFO - Started process 49448 to run task
[2024-02-27T23:13:08.988-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_customer_dag', 'read_s3_file_task', 'manual__2024-02-28T04:09:53.320788+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/etl_customer_dag.py', '--cfg-path', '/var/folders/0j/ct19m_4d33qfzqs3tkf7s7rm0000gq/T/tmpe8v6lp67']
[2024-02-27T23:13:08.993-0500] {standard_task_runner.py:85} INFO - Job 87: Subtask read_s3_file_task
[2024-02-27T23:13:09.201-0500] {task_command.py:416} INFO - Running <TaskInstance: etl_customer_dag.read_s3_file_task manual__2024-02-28T04:09:53.320788+00:00 [running]> on host venkatasaismbp.mynetworksettings.com
[2024-02-27T23:13:09.462-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Venkata' AIRFLOW_CTX_DAG_ID='etl_customer_dag' AIRFLOW_CTX_TASK_ID='read_s3_file_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-28T04:09:53.320788+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-28T04:09:53.320788+00:00'
[2024-02-27T23:13:09.527-0500] {base.py:73} INFO - Using connection ID 'aws_conn_s3' for task execution.
[2024-02-27T23:13:09.528-0500] {connection_wrapper.py:382} INFO - AWS Connection (conn_id='aws_conn_s3', conn_type='aws') credentials retrieved from login and ***.
[2024-02-27T23:15:36.295-0500] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-02-27T23:15:36.309-0500] {process_utils.py:131} INFO - Sending 15 to group 49448. PIDs of all processes in the group: [49448]
[2024-02-27T23:15:36.310-0500] {process_utils.py:86} INFO - Sending the signal 15 to group 49448
[2024-02-27T23:16:36.317-0500] {process_utils.py:149} WARNING - process psutil.Process(pid=49448, name='Python', status='running', started='23:13:08') did not respond to SIGTERM. Trying SIGKILL
[2024-02-27T23:16:36.322-0500] {process_utils.py:86} INFO - Sending the signal 9 to group 49448
[2024-02-27T23:16:36.338-0500] {process_utils.py:79} INFO - Process psutil.Process(pid=49448, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='23:13:08') (49448) terminated with exit code -9
[2024-02-27T23:16:36.340-0500] {standard_task_runner.py:172} ERROR - Job 87 was killed before it finished (likely due to running out of memory)
