[2024-03-01T15:09:26.832-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_customer_dag.upload_to_s3 manual__2024-02-29T21:43:30.430028+00:00 [queued]>
[2024-03-01T15:09:26.939-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_customer_dag.upload_to_s3 manual__2024-02-29T21:43:30.430028+00:00 [queued]>
[2024-03-01T15:09:26.940-0500] {taskinstance.py:1361} INFO - Starting attempt 5 of 5
[2024-03-01T15:09:26.954-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-02-29 21:43:30.430028+00:00
[2024-03-01T15:09:26.959-0500] {standard_task_runner.py:57} INFO - Started process 53775 to run task
[2024-03-01T15:09:26.965-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_customer_dag', 'upload_to_s3', 'manual__2024-02-29T21:43:30.430028+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/etl_customer_dag.py', '--cfg-path', '/var/folders/0j/ct19m_4d33qfzqs3tkf7s7rm0000gq/T/tmpne7qz355']
[2024-03-01T15:09:26.969-0500] {standard_task_runner.py:85} INFO - Job 135: Subtask upload_to_s3
[2024-03-01T15:09:27.089-0500] {task_command.py:416} INFO - Running <TaskInstance: etl_customer_dag.upload_to_s3 manual__2024-02-29T21:43:30.430028+00:00 [running]> on host venkatasaismbp.hsd1.nj.comcast.net
[2024-03-01T15:09:27.272-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Venkata' AIRFLOW_CTX_DAG_ID='etl_customer_dag' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-29T21:43:30.430028+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-29T21:43:30.430028+00:00'
[2024-03-01T15:09:27.312-0500] {base.py:73} INFO - Using connection ID 'aws_conn_s3' for task execution.
[2024-03-01T15:09:27.314-0500] {connection_wrapper.py:382} INFO - AWS Connection (conn_id='aws_conn_s3', conn_type='aws') credentials retrieved from login and ***.
[2024-03-01T15:11:18.735-0500] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-03-01T15:11:18.745-0500] {process_utils.py:131} INFO - Sending 15 to group 53775. PIDs of all processes in the group: [53775]
[2024-03-01T15:11:18.746-0500] {process_utils.py:86} INFO - Sending the signal 15 to group 53775
[2024-03-01T15:12:18.767-0500] {process_utils.py:149} WARNING - process psutil.Process(pid=53775, name='Python', status='running', started='15:09:26') did not respond to SIGTERM. Trying SIGKILL
[2024-03-01T15:12:18.775-0500] {process_utils.py:86} INFO - Sending the signal 9 to group 53775
[2024-03-01T15:12:18.790-0500] {process_utils.py:79} INFO - Process psutil.Process(pid=53775, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='15:09:26') (53775) terminated with exit code -9
[2024-03-01T15:12:18.792-0500] {standard_task_runner.py:172} ERROR - Job 135 was killed before it finished (likely due to running out of memory)
