[2024-02-27T23:18:04.539-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_customer_dag.transfer_s3_to_redshift manual__2024-02-28T04:09:53.320788+00:00 [queued]>
[2024-02-27T23:18:04.549-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_customer_dag.transfer_s3_to_redshift manual__2024-02-28T04:09:53.320788+00:00 [queued]>
[2024-02-27T23:18:04.550-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-02-27T23:18:04.561-0500] {taskinstance.py:1382} INFO - Executing <Task(S3ToRedshiftOperator): transfer_s3_to_redshift> on 2024-02-28 04:09:53.320788+00:00
[2024-02-27T23:18:04.565-0500] {standard_task_runner.py:57} INFO - Started process 51088 to run task
[2024-02-27T23:18:04.570-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_customer_dag', 'transfer_s3_to_redshift', 'manual__2024-02-28T04:09:53.320788+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/etl_customer_dag.py', '--cfg-path', '/var/folders/0j/ct19m_4d33qfzqs3tkf7s7rm0000gq/T/tmpqfqw_osw']
[2024-02-27T23:18:04.572-0500] {standard_task_runner.py:85} INFO - Job 93: Subtask transfer_s3_to_redshift
[2024-02-27T23:18:04.698-0500] {task_command.py:416} INFO - Running <TaskInstance: etl_customer_dag.transfer_s3_to_redshift manual__2024-02-28T04:09:53.320788+00:00 [running]> on host venkatasaismbp.mynetworksettings.com
[2024-02-27T23:18:04.886-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Venkata' AIRFLOW_CTX_DAG_ID='etl_customer_dag' AIRFLOW_CTX_TASK_ID='transfer_s3_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-02-28T04:09:53.320788+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-28T04:09:53.320788+00:00'
[2024-02-27T23:18:04.925-0500] {base.py:73} INFO - Using connection ID 'aws_conn_s3' for task execution.
[2024-02-27T23:18:04.979-0500] {base.py:73} INFO - Using connection ID 'aws_conn_s3' for task execution.
[2024-02-27T23:18:04.980-0500] {connection_wrapper.py:382} INFO - AWS Connection (conn_id='aws_conn_s3', conn_type='aws') credentials retrieved from login and ***.
[2024-02-27T23:18:04.996-0500] {s3_to_redshift.py:193} INFO - Executing COPY command...
[2024-02-27T23:18:05.085-0500] {base.py:73} INFO - Using connection ID 'redshift_default' for task execution.
[2024-02-27T23:18:05.133-0500] {base.py:73} INFO - Using connection ID 'aws_default' for task execution.
[2024-02-27T23:19:00.529-0500] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-02-27T23:19:00.544-0500] {process_utils.py:131} INFO - Sending 15 to group 51088. PIDs of all processes in the group: [51088]
[2024-02-27T23:19:00.544-0500] {process_utils.py:86} INFO - Sending the signal 15 to group 51088
[2024-02-27T23:20:00.545-0500] {process_utils.py:149} WARNING - process psutil.Process(pid=51088, name='Python', status='running', started='23:18:04') did not respond to SIGTERM. Trying SIGKILL
[2024-02-27T23:20:00.551-0500] {process_utils.py:86} INFO - Sending the signal 9 to group 51088
[2024-02-27T23:20:00.566-0500] {process_utils.py:79} INFO - Process psutil.Process(pid=51088, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='23:18:04') (51088) terminated with exit code -9
[2024-02-27T23:20:00.567-0500] {standard_task_runner.py:172} ERROR - Job 93 was killed before it finished (likely due to running out of memory)
