[2024-02-27T23:15:30.173-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_customer_dag.remove_null_values_task manual__2024-02-28T04:09:53.320788+00:00 [queued]>
[2024-02-27T23:15:30.188-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_customer_dag.remove_null_values_task manual__2024-02-28T04:09:53.320788+00:00 [queued]>
[2024-02-27T23:15:30.189-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-02-27T23:15:30.201-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): remove_null_values_task> on 2024-02-28 04:09:53.320788+00:00
[2024-02-27T23:15:30.206-0500] {standard_task_runner.py:57} INFO - Started process 50164 to run task
[2024-02-27T23:15:30.213-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_customer_dag', 'remove_null_values_task', 'manual__2024-02-28T04:09:53.320788+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/etl_customer_dag.py', '--cfg-path', '/var/folders/0j/ct19m_4d33qfzqs3tkf7s7rm0000gq/T/tmpd2j0e61t']
[2024-02-27T23:15:30.216-0500] {standard_task_runner.py:85} INFO - Job 88: Subtask remove_null_values_task
[2024-02-27T23:15:30.367-0500] {task_command.py:416} INFO - Running <TaskInstance: etl_customer_dag.remove_null_values_task manual__2024-02-28T04:09:53.320788+00:00 [running]> on host venkatasaismbp.mynetworksettings.com
[2024-02-27T23:15:30.563-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Venkata' AIRFLOW_CTX_DAG_ID='etl_customer_dag' AIRFLOW_CTX_TASK_ID='remove_null_values_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-28T04:09:53.320788+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-28T04:09:53.320788+00:00'
[2024-02-27T23:15:30.569-0500] {logging_mixin.py:154} WARNING - /Users/venkatasaisabbineni/Desktop/Airflow_local/dags/etl_customer_dag.py:26 FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
[2024-02-27T23:15:30.570-0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/dags/etl_customer_dag.py", line 26, in remove_null_values
    df = pd.read_json(json_data)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/pandas/io/json/_json.py", line 815, in read_json
    return json_reader.read()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/pandas/io/json/_json.py", line 1025, in read
    obj = self._get_object_parser(self.data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/pandas/io/json/_json.py", line 1051, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/pandas/io/json/_json.py", line 1187, in parse
    self._parse()
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/pandas/io/json/_json.py", line 1403, in _parse
    ujson_loads(json, precise_float=self.precise_float), dtype=None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unexpected character found when decoding 'NaN'
[2024-02-27T23:15:30.613-0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_customer_dag, task_id=remove_null_values_task, execution_date=20240228T040953, start_date=20240228T041530, end_date=20240228T041530
[2024-02-27T23:15:30.624-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 88 for task remove_null_values_task (Unexpected character found when decoding 'NaN'; 50164)
[2024-02-27T23:15:30.637-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-02-27T23:15:30.695-0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
