[2024-02-26T07:11:15.138-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline.insert_customers manual__2024-02-26T12:10:40.945296+00:00 [queued]>
[2024-02-26T07:11:15.141-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline.insert_customers manual__2024-02-26T12:10:40.945296+00:00 [queued]>
[2024-02-26T07:11:15.141-0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-02-26T07:11:15.147-0500] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_customers> on 2024-02-26 12:10:40.945296+00:00
[2024-02-26T07:11:15.149-0500] {standard_task_runner.py:57} INFO - Started process 87684 to run task
[2024-02-26T07:11:15.153-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_pipeline', 'insert_customers', 'manual__2024-02-26T12:10:40.945296+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/postgres_pipeline.py', '--cfg-path', '/var/folders/0j/ct19m_4d33qfzqs3tkf7s7rm0000gq/T/tmpeasi1kf2']
[2024-02-26T07:11:15.154-0500] {standard_task_runner.py:85} INFO - Job 62: Subtask insert_customers
[2024-02-26T07:11:15.182-0500] {task_command.py:416} INFO - Running <TaskInstance: postgres_pipeline.insert_customers manual__2024-02-26T12:10:40.945296+00:00 [running]> on host venkatasaismbp.mynetworksettings.com
[2024-02-26T07:11:15.207-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Venkata' AIRFLOW_CTX_DAG_ID='postgres_pipeline' AIRFLOW_CTX_TASK_ID='insert_customers' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T12:10:40.945296+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T12:10:40.945296+00:00'
[2024-02-26T07:11:15.208-0500] {sql.py:274} INFO - Executing: INSERT INTO customers (id, name) VALUES (1, 'Janice Smith');
INSERT INTO customers (id, name) VALUES (2, 'Ronald Jones');
INSERT INTO customers (id, name) VALUES (3, 'Kiele West');
INSERT INTO customers (id, name) VALUES (4, 'Leonard Cruise');
INSERT INTO customers (id, name) VALUES (5, 'Rihanna Luis');
INSERT INTO customers (id, name) VALUES (6, 'Koma Day-Lewis');
[2024-02-26T07:11:15.211-0500] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2024-02-26T07:11:15.291-0500] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2024-02-26T07:11:15.334-0500] {sql.py:418} INFO - Running statement: INSERT INTO customers (id, name) VALUES (1, 'Janice Smith');
INSERT INTO customers (id, name) VALUES (2, 'Ronald Jones');
INSERT INTO customers (id, name) VALUES (3, 'Kiele West');
INSERT INTO customers (id, name) VALUES (4, 'Leonard Cruise');
INSERT INTO customers (id, name) VALUES (5, 'Rihanna Luis');
INSERT INTO customers (id, name) VALUES (6, 'Koma Day-Lewis');, parameters: None
[2024-02-26T07:11:15.335-0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "customers_pkey"
DETAIL:  Key (id)=(1) already exists.

[2024-02-26T07:11:15.339-0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=postgres_pipeline, task_id=insert_customers, execution_date=20240226T121040, start_date=20240226T121115, end_date=20240226T121115
[2024-02-26T07:11:15.344-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 62 for task insert_customers (duplicate key value violates unique constraint "customers_pkey"
DETAIL:  Key (id)=(1) already exists.
; 87684)
[2024-02-26T07:11:15.349-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-02-26T07:11:15.356-0500] {logging_mixin.py:154} WARNING - /Users/venkatasaisabbineni/Desktop/Airflow_local/airflow_env/lib/python3.11/site-packages/airflow/models/baseoperator.py:1203 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-02-26T07:11:15.362-0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
